name: eslint-plugin-me CI
on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.11.1
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm i
      - name: Run Tests
        run: pnpm run test
      - name: Type Check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Build package
        run: pnpm run build
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            dis
            package.json
            README.md
            LICENSE
          retention-days: 1
  publish:
    if: github.ref == 'refs/heads/release'
    needs: integration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: .
      - name: Setup Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
